### ISSUE TITLE
Embed a JavaScript interpreter in the same way Lua is embedded.

### ISSUE THREAD

**Issue by birchb1024** [birchb1024/goyamp#11]
As a JavaScript programmer I would like to embed JavaScript in the macros so that I can write complex expansions or reductions in JavaScript. Example:

```YAML
JavaScript:
    args: $some-variables
    script:
          result = javascript_function(args)
```
