### ISSUE TITLE
Add 'patch' feature simliar to Kubertes' Kustomize 

### ISSUE THREAD

**Issue by birchb1024** [birchb1024/goyamp#13]
Kustomize has sed-like features which allow matching on a subtree (patch) or on maps with multiple keys, unlike Goyamp which currently matches on a single key.  This enhancement would add rewrite logic in a similar way. Perhaps something like this:
```
define:
    $some-input:
         foo:
            alpha: 23
            bar:
               quux:
---
patch:
    - $some-input
    - foo:
         bar: 42
```
Outputs
```
foo:
  alpha: 23
  bar: 42
```
