### ISSUE TITLE
Add multi-key matching for macros

### ISSUE THREAD

**Issue by birchb1024** [birchb1024/goyamp#14]
Kustomize has sed-like features which allow matching on a subtree (patch) or on maps with multiple keys, unlike Goyamp which currently matches on a single key.  This enhancement would add rewrite logic in a similar way. Perhaps something like this:
```
define:
    $some-input:
         foo:
            alpha: 23
            bar:
               quux:
---
defmultimacro:
    where:
          id: 23
          name: someresource
    args: [$this] 
    value:
          $this.id
          name: file-resource
---
$some-input
```
Outputs
```
foo:
  id: 23
  name: file-resource
```

It's a start.
