### ISSUE TITLE
Want to use repeat: on maps

### ISSUE THREAD

**Issue by birchb1024** [birchb1024/goyamp#3]
Example:
```
foo:
 a: 1
 b: 2
---
repeat:
   for: [$key, $value]
   in: foo
   body:
       - key = {{ $key }}, value = {{ $value }}
``` 
Or with just the keys:
```
---
repeat:
   for: $key
   in: foo
   body:
       - key = {{ key }}, value = {{ foo.$key }}
```
We currently get 
`
Error: Syntax error in repeat 'in' is not a seqeunce, got "foo" in { repeat : { body : [ key = {{ key }}, value = {{ foo.$key }} ] , for : $key , in : foo  }  }                                                   
`
