### ISSUE TITLE
Follow-up to yamp #13

### ISSUE THREAD

**Issue by daykin** [birchb1024/goyamp#5]
Hi again, and thanks for pointing me here. The example in 
[yamp issue 13](https://github.com/birchb1024/yamp/issues/13#event-3095489888) works as advertised for me with goyamp. One more question though: Is it possible to do something like this instead?
```
#foo.yaml is same as before
- include [foo.yaml]
---
- defmacro:
    name: bar
    args: [arg1, arg2, newArg]
    value:
        "{{arg1}}_{{arg2}}":
          - thisistoplevel: "OK"
          - {foo: {fooarg1: "{{arg1}}", fooarg2: "{{arg2}}", fooarg3: nested}}
---
- { bar: {arg1: bogus, arg2: example, newArg: 1}}
```

When I try to do this, it doesn't recognize the 'include' statement, and in turn doesn't expand the `foo...` item.
